general:
  seed: 901
quclassi_options:
  structure: "s"
trainer_options:
  epochs: 25
  learning_rate: 0.01
  batch_size: 1
  shuffle: True
  initial_paramters: Null
  shots: 8000
  eval: False
  model_dir_path: "./models/wine"
dataset_options:
  name: wine
  should_scale: False
  train_size: 0.75
  shuffle: True
